# Generated by Django 4.2.5 on 2023-10-03 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_alter_férias_dias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='férias',
            name='dias',
            field=models.IntegerField(),
        ),
    ]
